if(NOT DEFINED CODEGEN)
    message(FATAL_ERROR "CODEGEN is required")
endif()
if(NOT DEFINED DATA_DIR)
    message(FATAL_ERROR "DATA_DIR is required")
endif()
if(NOT DEFINED FULL_BUILD)
    set(FULL_BUILD 1)
endif()

function(run_ok outvar errvar)
    execute_process(
        COMMAND ${ARGN}
        RESULT_VARIABLE result
        OUTPUT_VARIABLE output
        ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Command failed (${result}): ${ARGN}\nstdout:\n${output}\nstderr:\n${error}")
    endif()
    set(${outvar} "${output}" PARENT_SCOPE)
    set(${errvar} "${error}" PARENT_SCOPE)
endfunction()

function(run_fail outvar errvar)
    execute_process(
        COMMAND ${ARGN}
        RESULT_VARIABLE result
        OUTPUT_VARIABLE output
        ERROR_VARIABLE error)
    if(result EQUAL 0)
        message(FATAL_ERROR "Command unexpectedly succeeded: ${ARGN}\nstdout:\n${output}\nstderr:\n${error}")
    endif()
    set(${outvar} "${output}" PARENT_SCOPE)
    set(${errvar} "${error}" PARENT_SCOPE)
endfunction()

function(normalize_generated input output_var)
    string(REGEX REPLACE "// Source: [^\n]*\n" "// Source: <normalized>\n" normalized "${input}")
    set(${output_var} "${normalized}" PARENT_SCOPE)
endfunction()

set(proto2 "${DATA_DIR}/integration-proto2.proto")
set(pbs2 "${DATA_DIR}/integration-proto2.pbs")
set(proto3 "${DATA_DIR}/integration-proto3.proto")
set(pbs3 "${DATA_DIR}/integration-proto3.pbs")

run_ok(pbs2_explicit pbs2_explicit_err ${CODEGEN} --descriptor-set ${pbs2})
string(FIND "${pbs2_explicit}" "#pragma once" pragma_once_pos)
if(pragma_once_pos EQUAL -1)
    message(FATAL_ERROR "Generated C++ header lacks #pragma once")
endif()
run_ok(pbs2_implicit pbs2_implicit_err ${CODEGEN} ${pbs2})
if(NOT pbs2_explicit STREQUAL pbs2_implicit)
    message(FATAL_ERROR "Explicit and implicit descriptor-set outputs differ")
endif()

run_fail(empty_out empty_err ${CODEGEN} --descriptor-set ${DATA_DIR}/empty.pbs)
if(NOT empty_err MATCHES "contains no FileDescriptorProto")
    message(FATAL_ERROR "Empty descriptor-set error is unclear: ${empty_err}")
endif()
run_fail(multi_out multi_err ${CODEGEN} --descriptor-set ${DATA_DIR}/integration-multi.pbs)
if(NOT multi_err MATCHES "exactly one is required")
    message(FATAL_ERROR "Multi-file descriptor-set error is unclear: ${multi_err}")
endif()



# Nested message definitions are lexical C++ nested types.  Both source and
# descriptor-set inputs must produce the same output, and recursive by-value
# message graphs must fail before any partial header is emitted.
set(nested_proto "${DATA_DIR}/nested-messages.proto")
set(nested_pbs "${DATA_DIR}/nested-messages.pbs")
set(forward_proto "${DATA_DIR}/nested-forward.proto")
set(forward_pbs "${DATA_DIR}/nested-forward.pbs")
set(recursive_proto "${DATA_DIR}/nested-recursive.proto")
set(recursive_pbs "${DATA_DIR}/nested-recursive.pbs")
set(mutual_pbs "${DATA_DIR}/nested-mutual.pbs")
set(ancestor_pbs "${DATA_DIR}/nested-ancestor-recursive.pbs")
set(lexical_cycle_pbs "${DATA_DIR}/nested-lexical-cycle.pbs")
set(repeated_recursive_pbs "${DATA_DIR}/nested-recursive-repeated.pbs")
set(map_recursive_pbs "${DATA_DIR}/nested-recursive-map.pbs")

run_ok(nested_pbs_out nested_pbs_err ${CODEGEN} --descriptor-set ${nested_pbs})
string(FIND "${nested_pbs_out}" "struct Outer" nested_outer_pos)
string(FIND "${nested_pbs_out}" "struct Inner" nested_inner_pos)
string(FIND "${nested_pbs_out}" "struct Leaf" nested_leaf_pos)
string(FIND "${nested_pbs_out}" "Outer::Inner item;" nested_holder_pos)
string(FIND "${nested_pbs_out}" "std::map<std::string,Outer::Inner> by_name;" nested_map_pos)
string(FIND "${nested_pbs_out}" "const Outer::Inner::Leaf &x" nested_leaf_encoder_pos)
if(nested_outer_pos EQUAL -1 OR nested_inner_pos EQUAL -1 OR nested_leaf_pos EQUAL -1 OR
   nested_holder_pos EQUAL -1 OR nested_map_pos EQUAL -1 OR nested_leaf_encoder_pos EQUAL -1)
    message(FATAL_ERROR "Nested message output is incomplete:\n${nested_pbs_out}")
endif()

string(FIND "${nested_pbs_out}" "EASYPB_Outer_Inner_EXTRA_FIELDS" nested_macro_pos)
if(nested_macro_pos EQUAL -1)
    message(FATAL_ERROR "Nested insertion macro name is not flattened correctly")
endif()

run_ok(nested_no_class nested_no_class_err ${CODEGEN} --descriptor-set --no-class ${nested_pbs})
if(nested_no_class MATCHES "struct Outer" OR nested_no_class MATCHES "struct Inner")
    message(FATAL_ERROR "--no-class emitted nested structures")
endif()
if(NOT nested_no_class MATCHES "const Outer::Inner::Leaf &x")
    message(FATAL_ERROR "--no-class suppressed nested codecs")
endif()

run_ok(nested_no_encoder nested_no_encoder_err ${CODEGEN} --descriptor-set --no-encoder ${nested_pbs})
if(nested_no_encoder MATCHES "inline void encode")
    message(FATAL_ERROR "--no-encoder emitted nested encoders")
endif()
if(NOT nested_no_encoder MATCHES "inline void decode")
    message(FATAL_ERROR "--no-encoder unexpectedly suppressed nested decoders")
endif()

run_ok(nested_no_decoder nested_no_decoder_err ${CODEGEN} --descriptor-set --no-decoder ${nested_pbs})
if(nested_no_decoder MATCHES "inline void decode")
    message(FATAL_ERROR "--no-decoder emitted nested decoders")
endif()
if(NOT nested_no_decoder MATCHES "inline void encode")
    message(FATAL_ERROR "--no-decoder unexpectedly suppressed nested encoders")
endif()

run_ok(forward_pbs_out forward_pbs_err ${CODEGEN} --descriptor-set ${forward_pbs})
string(FIND "${forward_pbs_out}" "struct First" forward_first_pos)
string(FIND "${forward_pbs_out}" "struct Second" forward_second_pos)
string(FIND "${forward_pbs_out}" "struct A" forward_a_pos)
string(FIND "${forward_pbs_out}" "struct B" forward_b_pos)
if(forward_first_pos EQUAL -1 OR forward_second_pos EQUAL -1 OR
   NOT forward_second_pos LESS forward_first_pos OR
   forward_a_pos EQUAL -1 OR forward_b_pos EQUAL -1 OR
   NOT forward_b_pos LESS forward_a_pos)
    message(FATAL_ERROR "Forward message dependencies were not ordered correctly:\n${forward_pbs_out}")
endif()

run_fail(recursive_pbs_out recursive_pbs_err ${CODEGEN} --descriptor-set ${recursive_pbs})
if(NOT recursive_pbs_err MATCHES "recursive message value dependency")
    message(FATAL_ERROR "Self-recursive message error is unclear: ${recursive_pbs_err}")
endif()
if(NOT recursive_pbs_out STREQUAL "")
    message(FATAL_ERROR "Recursive descriptor emitted partial generated output")
endif()

run_fail(mutual_pbs_out mutual_pbs_err ${CODEGEN} --descriptor-set ${mutual_pbs})
if(NOT mutual_pbs_err MATCHES "recursive message value dependency")
    message(FATAL_ERROR "Mutually recursive message error is unclear: ${mutual_pbs_err}")
endif()
if(NOT mutual_pbs_out STREQUAL "")
    message(FATAL_ERROR "Mutually recursive descriptor emitted partial generated output")
endif()


run_fail(ancestor_pbs_out ancestor_pbs_err ${CODEGEN} --descriptor-set ${ancestor_pbs})
if(NOT ancestor_pbs_err MATCHES "recursive message value dependency")
    message(FATAL_ERROR "Nested ancestor dependency error is unclear: ${ancestor_pbs_err}")
endif()
if(NOT ancestor_pbs_out STREQUAL "")
    message(FATAL_ERROR "Nested ancestor dependency emitted partial generated output")
endif()

run_fail(lexical_cycle_out lexical_cycle_err ${CODEGEN} --descriptor-set ${lexical_cycle_pbs})
if(NOT lexical_cycle_err MATCHES "recursive message value dependency")
    message(FATAL_ERROR "Lexical root dependency cycle error is unclear: ${lexical_cycle_err}")
endif()
if(NOT lexical_cycle_out STREQUAL "")
    message(FATAL_ERROR "Lexical root dependency cycle emitted partial generated output")
endif()


run_fail(repeated_recursive_out repeated_recursive_err ${CODEGEN} --descriptor-set ${repeated_recursive_pbs})
if(NOT repeated_recursive_err MATCHES "recursive message value dependency")
    message(FATAL_ERROR "Repeated recursive message error is unclear: ${repeated_recursive_err}")
endif()
if(NOT repeated_recursive_out STREQUAL "")
    message(FATAL_ERROR "Repeated recursive message emitted partial generated output")
endif()

run_fail(map_recursive_out map_recursive_err ${CODEGEN} --descriptor-set ${map_recursive_pbs})
if(NOT map_recursive_err MATCHES "recursive message value dependency")
    message(FATAL_ERROR "Recursive message-map error is unclear: ${map_recursive_err}")
endif()
if(NOT map_recursive_out STREQUAL "")
    message(FATAL_ERROR "Recursive message-map emitted partial generated output")
endif()

if(FULL_BUILD)
    run_ok(nested_proto_out nested_proto_err ${CODEGEN} ${nested_proto})
    normalize_generated("${nested_pbs_out}" nested_pbs_normalized)
    normalize_generated("${nested_proto_out}" nested_proto_normalized)
    if(NOT nested_proto_normalized STREQUAL nested_pbs_normalized)
        message(FATAL_ERROR "Nested .proto and .pbs generated outputs differ")
    endif()

    run_ok(forward_proto_out forward_proto_err ${CODEGEN} ${forward_proto})
    normalize_generated("${forward_pbs_out}" forward_pbs_normalized)
    normalize_generated("${forward_proto_out}" forward_proto_normalized)
    if(NOT forward_proto_normalized STREQUAL forward_pbs_normalized)
        message(FATAL_ERROR "Nested forward .proto and .pbs generated outputs differ")
    endif()

    run_fail(recursive_proto_out recursive_proto_err ${CODEGEN} ${recursive_proto})
    if(NOT recursive_proto_err MATCHES "recursive message value dependency")
        message(FATAL_ERROR "Source self-recursive message error is unclear: ${recursive_proto_err}")
    endif()
    if(NOT recursive_proto_out STREQUAL "")
        message(FATAL_ERROR "Recursive source emitted partial generated output")
    endif()
    run_ok(src2 src2_err ${CODEGEN} ${proto2})
    normalize_generated("${src2}" src2_norm)
    normalize_generated("${pbs2_explicit}" pbs2_norm)
    if(NOT src2_norm STREQUAL pbs2_norm)
        file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/source-proto2.hpp" "${src2_norm}")
        file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/descriptor-proto2.hpp" "${pbs2_norm}")
        message(FATAL_ERROR "Proto2 source and descriptor-set outputs differ")
    endif()

    run_ok(src3 src3_err ${CODEGEN} ${proto3})
    run_ok(pbs3_out pbs3_err ${CODEGEN} --descriptor-set ${pbs3})
    normalize_generated("${src3}" src3_norm)
    normalize_generated("${pbs3_out}" pbs3_norm)
    if(NOT src3_norm STREQUAL pbs3_norm)
        file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/source-proto3.hpp" "${src3_norm}")
        file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/descriptor-proto3.hpp" "${pbs3_norm}")
        message(FATAL_ERROR "Proto3 source and descriptor-set outputs differ")
    endif()

    string(FIND "${src3}" "put_packed_int32(1, x.implicit_packed)" implicit_pos)
    if(implicit_pos EQUAL -1)
        message(FATAL_ERROR "Implicit proto3 packed default was not applied")
    endif()
    string(FIND "${src3}" "put_repeated_int32(2, x.explicit_unpacked)" explicit_pos)
    if(explicit_pos EQUAL -1)
        message(FATAL_ERROR "Explicit packed=false was not applied")
    endif()
    run_ok(force_unpacked force_unpacked_err ${CODEGEN} --no-packed ${proto3})
    string(FIND "${force_unpacked}" "put_repeated_int32(1, x.implicit_packed)" force_unpacked_pos)
    if(force_unpacked_pos EQUAL -1)
        message(FATAL_ERROR "--no-packed did not override proto3 default")
    endif()
    run_ok(force_packed force_packed_err ${CODEGEN} --packed ${proto3})
    string(FIND "${force_packed}" "put_packed_int32(2, x.explicit_unpacked)" force_packed_pos)
    if(force_packed_pos EQUAL -1)
        message(FATAL_ERROR "--packed did not override explicit packed=false")
    endif()

    run_ok(print_out print_err ${CODEGEN} --print-descriptor ${proto2})
    if(NOT print_out MATCHES "message Proto2Message")
        message(FATAL_ERROR "Pretty-printer output lacks descriptor tree: ${print_out}")
    endif()
    if(print_out MATCHES "Generated by EasyProtoBuf")
        message(FATAL_ERROR "Pretty-printer emitted generated C++")
    endif()

    run_ok(print_pbs_out print_pbs_err ${CODEGEN} --descriptor-set --print-descriptor ${pbs2})
    if(NOT print_pbs_out MATCHES "message Proto2Message")
        message(FATAL_ERROR "Descriptor-set pretty-printer failed")
    endif()

    run_ok(bench_out bench_err ${CODEGEN} --benchmark-parser --benchmark-ms 100
        ${proto2} ${DATA_DIR}/benchmark-second.proto)
    if(NOT bench_out MATCHES "Files: 2")
        message(FATAL_ERROR "Benchmark did not process both files: ${bench_out}")
    endif()
    if(NOT bench_out MATCHES "Warm-up rounds: 1")
        message(FATAL_ERROR "Benchmark warm-up is missing: ${bench_out}")
    endif()
    string(REGEX MATCH "in ([0-9]+\\.[0-9]+) s" time_match "${bench_out}")
    set(seconds "${CMAKE_MATCH_1}")
    if(seconds STREQUAL "" OR seconds LESS 0.100)
        message(FATAL_ERROR "Benchmark ran for less than 100 ms: ${bench_out}")
    endif()

    run_fail(bad_bench_out bad_bench_err ${CODEGEN} --benchmark-parser --no-class ${proto2})
    if(NOT bad_bench_err MATCHES "code-generation options")
        message(FATAL_ERROR "Benchmark accepted generation options: ${bad_bench_err}")
    endif()

    run_ok(rpc_out rpc_err ${CODEGEN} ${DATA_DIR}/service-rpc.proto)
    string(FIND "${rpc_out}" "struct Request" rpc_request_pos)
    string(FIND "${rpc_out}" "struct Reply" rpc_reply_pos)
    string(FIND "${rpc_out}" "struct AfterService" rpc_after_pos)
    string(FIND "${rpc_out}" "Greeter" rpc_service_pos)
    if(rpc_request_pos EQUAL -1 OR rpc_reply_pos EQUAL -1 OR rpc_after_pos EQUAL -1)
        message(FATAL_ERROR "RPC source did not generate all message structures: ${rpc_out}")
    endif()
    if(NOT rpc_service_pos EQUAL -1)
        message(FATAL_ERROR "Service declaration leaked into generated C++: ${rpc_out}")
    endif()

    run_fail(unresolved_out unresolved_err ${CODEGEN} ${DATA_DIR}/unresolved.proto)
    if(NOT unresolved_err MATCHES "--descriptor-set")
        message(FATAL_ERROR "Unresolved type error does not mention descriptor-set input: ${unresolved_err}")
    endif()
else()
    run_fail(source_out source_err ${CODEGEN} ${proto2})
    if(NOT source_err MATCHES "no .proto parser")
        message(FATAL_ERROR "Lite build source error is unclear: ${source_err}")
    endif()
    run_fail(print_out print_err ${CODEGEN} --print-descriptor ${pbs2})
    run_fail(bench_out bench_err ${CODEGEN} --benchmark-parser ${proto2})
endif()
