// Generated by EasyProtoBuf Codegen.  DO NOT EDIT!
// Source: tutorial.pbs

#include <cstdint>
#include <string>
#include <vector>
#include <map>

#include <easypb.hpp>


struct SubMessage
{
    int64_t req_int64 = 0;
    int32_t opt_sint32 = 0;
    uint64_t req_uint64 = 0;
    uint32_t opt_fixed32 = 0;
    float req_float = 0;
    std::string opt_string = "DEFAULT STRING";
    std::vector<int32_t> rep_int32;
    std::vector<uint64_t> rep_uint64;
    std::vector<double> rep_double;

    bool has_req_int64 = false;
    bool has_opt_sint32 = false;
    bool has_req_uint64 = false;
    bool has_opt_fixed32 = false;
    bool has_req_float = false;
    bool has_opt_string = false;

#ifdef EASYPB_SubMessage_EXTRA_FIELDS
EASYPB_SubMessage_EXTRA_FIELDS
#endif
};

inline void encode(easypb::Encoder &pb, const SubMessage &x)
{
    pb.put_int64(1, x.req_int64);
    pb.put_sint32(2, x.opt_sint32);
    pb.put_uint64(3, x.req_uint64);
    pb.put_fixed32(4, x.opt_fixed32);
    pb.put_float(5, x.req_float);
    pb.put_string(6, x.opt_string);
    pb.put_repeated_int32(11, x.rep_int32);
    pb.put_repeated_uint64(12, x.rep_uint64);
    pb.put_repeated_double(13, x.rep_double);

#ifdef EASYPB_SubMessage_EXTRA_ENCODING
EASYPB_SubMessage_EXTRA_ENCODING(pb, x)
#endif
}

inline void decode(easypb::Decoder pb, SubMessage &x)
{
    while(pb.get_next_field())
    {
        switch(pb.field_num)
        {
            case 1: pb.get_int64(&x.req_int64, &x.has_req_int64); break;
            case 2: pb.get_sint32(&x.opt_sint32, &x.has_opt_sint32); break;
            case 3: pb.get_uint64(&x.req_uint64, &x.has_req_uint64); break;
            case 4: pb.get_fixed32(&x.opt_fixed32, &x.has_opt_fixed32); break;
            case 5: pb.get_float(&x.req_float, &x.has_req_float); break;
            case 6: pb.get_string(&x.opt_string, &x.has_opt_string); break;
            case 11: pb.get_repeated_int32(&x.rep_int32); break;
            case 12: pb.get_repeated_uint64(&x.rep_uint64); break;
            case 13: pb.get_repeated_double(&x.rep_double); break;

#ifdef EASYPB_SubMessage_EXTRA_DECODING
EASYPB_SubMessage_EXTRA_DECODING(pb, x)
#endif
            default: pb.skip_field();
        }
    }
#ifdef EASYPB_SubMessage_EXTRA_POST_DECODING
EASYPB_SubMessage_EXTRA_POST_DECODING(pb, x)
#endif

    if(! x.has_req_int64) {
        throw easypb::missing_required_field("Decoded protobuf has no required field SubMessage.req_int64");
    }

    if(! x.has_req_uint64) {
        throw easypb::missing_required_field("Decoded protobuf has no required field SubMessage.req_uint64");
    }

    if(! x.has_req_float) {
        throw easypb::missing_required_field("Decoded protobuf has no required field SubMessage.req_float");
    }

}

struct MainMessage
{
    uint32_t opt_uint32 = 0;
    int64_t req_sfixed64 = 0;
    double opt_double = 3.14;
    std::string req_bytes;
    SubMessage req_msg;
    std::vector<int32_t> rep_sint32;
    std::vector<uint64_t> rep_fixed64;
    std::vector<std::string> rep_string;
    std::vector<SubMessage> rep_msg;
    std::map<int32_t,int32_t> mappa;

    bool has_opt_uint32 = false;
    bool has_req_sfixed64 = false;
    bool has_opt_double = false;
    bool has_req_bytes = false;
    bool has_req_msg = false;

#ifdef EASYPB_MainMessage_EXTRA_FIELDS
EASYPB_MainMessage_EXTRA_FIELDS
#endif
};

inline void encode(easypb::Encoder &pb, const MainMessage &x)
{
    pb.put_uint32(1, x.opt_uint32);
    pb.put_sfixed64(2, x.req_sfixed64);
    pb.put_double(3, x.opt_double);
    pb.put_bytes(4, x.req_bytes);
    pb.put_message(5, x.req_msg);
    pb.put_repeated_sint32(11, x.rep_sint32);
    pb.put_repeated_fixed64(12, x.rep_fixed64);
    pb.put_repeated_string(13, x.rep_string);
    pb.put_repeated_message(14, x.rep_msg);
    pb.put_map_int32_int32(15, x.mappa);

#ifdef EASYPB_MainMessage_EXTRA_ENCODING
EASYPB_MainMessage_EXTRA_ENCODING(pb, x)
#endif
}

inline void decode(easypb::Decoder pb, MainMessage &x)
{
    while(pb.get_next_field())
    {
        switch(pb.field_num)
        {
            case 1: pb.get_uint32(&x.opt_uint32, &x.has_opt_uint32); break;
            case 2: pb.get_sfixed64(&x.req_sfixed64, &x.has_req_sfixed64); break;
            case 3: pb.get_double(&x.opt_double, &x.has_opt_double); break;
            case 4: pb.get_bytes(&x.req_bytes, &x.has_req_bytes); break;
            case 5: pb.get_message(&x.req_msg, &x.has_req_msg); break;
            case 11: pb.get_repeated_sint32(&x.rep_sint32); break;
            case 12: pb.get_repeated_fixed64(&x.rep_fixed64); break;
            case 13: pb.get_repeated_string(&x.rep_string); break;
            case 14: pb.get_repeated_message(&x.rep_msg); break;
            case 15: pb.get_map_int32_int32(&x.mappa); break;

#ifdef EASYPB_MainMessage_EXTRA_DECODING
EASYPB_MainMessage_EXTRA_DECODING(pb, x)
#endif
            default: pb.skip_field();
        }
    }
#ifdef EASYPB_MainMessage_EXTRA_POST_DECODING
EASYPB_MainMessage_EXTRA_POST_DECODING(pb, x)
#endif

    if(! x.has_req_sfixed64) {
        throw easypb::missing_required_field("Decoded protobuf has no required field MainMessage.req_sfixed64");
    }

    if(! x.has_req_bytes) {
        throw easypb::missing_required_field("Decoded protobuf has no required field MainMessage.req_bytes");
    }

    if(! x.has_req_msg) {
        throw easypb::missing_required_field("Decoded protobuf has no required field MainMessage.req_msg");
    }

}
