#include <iostream>
#include <map>
#include <stdexcept>
#include <string>

#include <easypb.hpp>
#include "descriptor.pb.cpp"
#include "utils.cpp"


// Command-line options affecting the generated code
struct
{
    bool no_class = false;
    bool no_decoder = false;
    bool no_encoder = false;
    bool no_has_fields = false;
    bool no_required = false;
    bool no_default_values = false;
    bool packed = false;
    bool no_packed = false;
    std::string cpp_string_type;
    std::string cpp_repeated_type;
    std::string cpp_map_type;
} option;


// Protobuf and C++ delimiters between parts of a qualified name
const std::string PB_TYPE_DELIMITER = ".";
const std::string CPP_TYPE_DELIMITER = "::";


// A few global vars instead of passing data between functions
std::string package_name_prefix;  // package-describing prefix of message types, e.g. ".mypackage."
std::string msgtype_name_prefix;  // extra message-type-describing prefix of message types, e.g. "Msg."


const char* FILE_TEMPLATE =
R"---(// Generated by EasyProtoBuf Codegen.  DO NOT EDIT!
// Source: {0}

#include <cstdint>
#include <string>
#include <vector>
#include <map>

#include <easypb.hpp>

)---";


// {0}=message_type.name, {1}=field_defs, {2}=has_field_defs
const char* CLASS_TEMPLATE = R"---(
struct {0}
{
{1}
{2}
#ifdef EASYPB_{0}_EXTRA_FIELDS
EASYPB_{0}_EXTRA_FIELDS
#endif
};
)---";


// {0}=message_type.name, {1}=encoder
const char* ENCODER_TEMPLATE = R"---(
inline void encode(easypb::Encoder &pb, const {0} &x)
{
{1}
#ifdef EASYPB_{0}_EXTRA_ENCODING
EASYPB_{0}_EXTRA_ENCODING(pb, x)
#endif
}
)---";


// {0}=message_type.name, {1}=decoder, {2}=check_required_fields
const char* DECODER_TEMPLATE = R"---(
inline void decode(easypb::Decoder pb, {0} &x)
{
    while(pb.get_next_field())
    {
        switch(pb.field_num)
        {
{1}
#ifdef EASYPB_{0}_EXTRA_DECODING
EASYPB_{0}_EXTRA_DECODING(pb, x)
#endif
            default: pb.skip_field();
        }
    }
#ifdef EASYPB_{0}_EXTRA_POST_DECODING
EASYPB_{0}_EXTRA_POST_DECODING(pb, x)
#endif
{2}
}
)---";


// {0}=message_type.name, {1}=field.name
const char* CHECK_REQUIRED_FIELD_TEMPLATE = R"---(
    if(! x.has_{1}) {
        throw easypb::missing_required_field("Decoded protobuf has no required field {0}.{1}");
    }
)---";



// Is it a repeated Protobuf field?
bool is_repeated(const FieldDescriptorProto& field)
{
    return (field.label == FieldDescriptorProto::LABEL_REPEATED);
}


// Does this field have corresponding has_* flag?
bool hasfield_enabled(const FieldDescriptorProto& field)
{
    return (! is_repeated(field)  &&  ! option.no_has_fields);
}


// Is it a Protobuf numeric field (including enums/bools)?
bool is_numeric_field(const FieldDescriptorProto& field)
{
    return (field.type != FieldDescriptorProto::TYPE_STRING) &&
           (field.type != FieldDescriptorProto::TYPE_BYTES) &&
           (field.type != FieldDescriptorProto::TYPE_MESSAGE) &&
           (field.type != FieldDescriptorProto::TYPE_GROUP);
}


// Serialize this field in the more compact "packed" Protobuf wire format?
bool write_as_packed(const FieldDescriptorProto& field)
{
    return is_repeated(field) &&
           is_numeric_field(field) &&
           (option.packed ?    true :
            option.no_packed ? false :
                               field.options.packed);
}


// Either " = default_field_value" or empty string
std::string default_value_str(const FieldDescriptorProto& field)
{
    if (field.has_default_value  &&  ! option.no_default_values) {
        // Use default field value specified in .proto file
        bool is_bytearray_field = (field.type==FieldDescriptorProto::TYPE_STRING || field.type==FieldDescriptorProto::TYPE_BYTES);
        const char* quote_str = (is_bytearray_field? "\"" : "");
        return myformat(" = {0}{1}{0}", quote_str, field.default_value);
    } else if (is_repeated(field)) {
        return "";
    } else {
        // C++ doesn't initialize scalar fields by default, so we need to enforce the initialization
        return field.type == FieldDescriptorProto::TYPE_BOOL
                   ? " = false" :
               is_numeric_field(field)
                   ? " = 0"
               // or another field type
                   : "";
    }
}


// PB type as used in .proto file (e.g. "fixed32")
str_view pbtype_name(const FieldDescriptorProto& field)
{
    switch(field.type)
    {
        case FieldDescriptorProto::TYPE_DOUBLE:    return "double";
        case FieldDescriptorProto::TYPE_FLOAT:     return "float";
        case FieldDescriptorProto::TYPE_INT64:     return "int64";
        case FieldDescriptorProto::TYPE_UINT64:    return "uint64";
        case FieldDescriptorProto::TYPE_INT32:     return "int32";
        case FieldDescriptorProto::TYPE_FIXED64:   return "fixed64";
        case FieldDescriptorProto::TYPE_FIXED32:   return "fixed32";
        case FieldDescriptorProto::TYPE_BOOL:      return "bool";
        case FieldDescriptorProto::TYPE_STRING:    return "string";
        case FieldDescriptorProto::TYPE_GROUP:     return "???group";
        case FieldDescriptorProto::TYPE_MESSAGE:   return "message";
        case FieldDescriptorProto::TYPE_BYTES:     return "bytes";
        case FieldDescriptorProto::TYPE_UINT32:    return "uint32";
        case FieldDescriptorProto::TYPE_ENUM:      return "enum";
        case FieldDescriptorProto::TYPE_SFIXED32:  return "sfixed32";
        case FieldDescriptorProto::TYPE_SFIXED64:  return "sfixed64";
        case FieldDescriptorProto::TYPE_SINT32:    return "sint32";
        case FieldDescriptorProto::TYPE_SINT64:    return "sint64";
    }

    return "???type";
}


// Return the shortest [qualified] C++ type corresponding to the fully qualified Protobuf message/enum type
std::string cpp_qualified_type_str(str_view message_type)
{
    // Strip the package_name_prefix from the fully qualified message_type,
    // e.g. (".google.protobuf.", ".google.protobuf.DescriptorProto.ExtensionRange") -> "DescriptorProto.ExtensionRange",
    // then drop the prefix of the current msgtype (e.g. "DescriptorProto."),
    // and finally replace "." typename separator with "::"

    // If message type starts with ".PACKAGE_NAME.", drop this prefix
    auto pkg_prefix_len = package_name_prefix.length();
    if (message_type.substr(0, pkg_prefix_len) == package_name_prefix) {
        message_type = message_type.substr(pkg_prefix_len);

        // If message type starts with "CURRENT_MSGTYPE_NAME.", drop this prefix
        auto msg_prefix_len = msgtype_name_prefix.length();
        if (message_type.substr(0, msg_prefix_len) == msgtype_name_prefix) {
            message_type = message_type.substr(msg_prefix_len);
        }
    }

    // Finally, replace "." between name components with C++-specific "::"
    return string_replace_all(message_type, PB_TYPE_DELIMITER, CPP_TYPE_DELIMITER );
}


// Return C++ type corresponding to the base type (without "repeated") of the Protobuf field
std::string base_cpp_type_as_str(const FieldDescriptorProto& field)
{
    // According to https://github.com/protocolbuffers/protobuf/blob/c05b320d9c18173bfce36c4bef22f9953d340ff9/src/google/protobuf/descriptor.h#L780
    switch(field.type)
    {
        case FieldDescriptorProto::TYPE_INT32:
        case FieldDescriptorProto::TYPE_SINT32:
        case FieldDescriptorProto::TYPE_SFIXED32: return "int32_t";

        case FieldDescriptorProto::TYPE_INT64:
        case FieldDescriptorProto::TYPE_SINT64:
        case FieldDescriptorProto::TYPE_SFIXED64: return "int64_t";

        case FieldDescriptorProto::TYPE_UINT32:
        case FieldDescriptorProto::TYPE_FIXED32:  return "uint32_t";

        case FieldDescriptorProto::TYPE_UINT64:
        case FieldDescriptorProto::TYPE_FIXED64:  return "uint64_t";

        case FieldDescriptorProto::TYPE_DOUBLE:   return "double";

        case FieldDescriptorProto::TYPE_FLOAT:    return "float";

        case FieldDescriptorProto::TYPE_BOOL:     return "bool";

        case FieldDescriptorProto::TYPE_ENUM:     return "int32_t";

        case FieldDescriptorProto::TYPE_STRING:
        case FieldDescriptorProto::TYPE_BYTES:    return option.cpp_string_type;

        case FieldDescriptorProto::TYPE_MESSAGE:  return cpp_qualified_type_str(field.type_name);

        case FieldDescriptorProto::TYPE_GROUP:    return "???group";
    }

    return "???type";
}


struct MapType
{
    const FieldDescriptorProto* key_field = nullptr;
    const FieldDescriptorProto* value_field = nullptr;
};

using MapTypeByName = std::map<std::string, MapType>;


// PB type suffix used by Encoder/Decoder methods (e.g. "fixed32" or "map_string_int32")
std::string protobuf_type_as_str(const FieldDescriptorProto& field, const MapType* map_type)
{
    if (map_type) {
        return myformat("map_{0}_{1}",
                        pbtype_name(*map_type->key_field),
                        pbtype_name(*map_type->value_field));
    }

    return std::string(pbtype_name(field));
}

// Return C++ type for the Protobuf field
std::string cpp_type_as_str(const FieldDescriptorProto& field, const MapType* map_type)
{
    auto basetype_str = base_cpp_type_as_str(field);

    if (map_type) {
        return myformat(option.cpp_map_type,
                        base_cpp_type_as_str(*map_type->key_field),
                        base_cpp_type_as_str(*map_type->value_field));
    }

    if (is_repeated(field)) {
        return myformat(option.cpp_repeated_type, basetype_str);
    } else {
        return basetype_str;
    }
}


// Encoder code for a single field
std::string generate_field_encoder(const FieldDescriptorProto& field, const MapType* map_type)
{
    return myformat("    pb.put_{0}{1}({2}, {3});\n",
    /* 0 */ ! map_type && is_repeated(field)
                ? (write_as_packed(field)? "packed_" : "repeated_")
                : "",
    /* 1 */ protobuf_type_as_str(field, map_type),
    /* 2 */ std::to_string(field.number),
    /* 3 */ "x." + std::string(field.name));
}


// Decoder code for a single field
std::string generate_field_decoder(const FieldDescriptorProto& field, const MapType* map_type)
{
    return myformat("            case {0}: pb.get_{1}{2}(&{3}{4}); break;\n",
    /* 0 */ std::to_string(field.number),
    /* 1 */ ! map_type && is_repeated(field)? "repeated_" : "",
    /* 2 */ protobuf_type_as_str(field, map_type),
    /* 3 */ "x." + std::string(field.name),
    /* 4 */ hasfield_enabled(field)
                ? myformat(", &x.has_{0}", field.name)
                : "");
}


// Collect map types represented as the nested message types
MapTypeByName collect_map_types(const DescriptorProto& message_type)
{
    MapTypeByName result;

    for (const auto& nested_msgtype: message_type.nested_type)
    {
        if (nested_msgtype.options.map_entry)
        {
            MapType map_type;

            for (const auto& field: nested_msgtype.field)
            {
                switch (field.number) {
                    case 1:  map_type.key_field   = &field;  break;
                    case 2:  map_type.value_field = &field;  break;
                }
            }

            auto nested_name = std::string(nested_msgtype.name);
            auto qualified_name = package_name_prefix + msgtype_name_prefix + nested_name;

            if (! map_type.key_field || ! map_type.value_field) {
                throw std::runtime_error(
                    myformat("Malformed map entry {0}: fields 1 and 2 are required", qualified_name));
            }

            result[qualified_name] = map_type;
        }
    }

    return result;
}


// Find the synthetic map-entry message referenced by a repeated message field
const MapType* find_map_type(const FieldDescriptorProto& field, const MapTypeByName& maptype_by_name)
{
    if (! is_repeated(field) || field.type != FieldDescriptorProto::TYPE_MESSAGE) {
        return nullptr;
    }

    auto field_type_name = std::string(field.type_name);
    auto map_it = maptype_by_name.find(field_type_name);
    if (map_it == maptype_by_name.end()) {
        return nullptr;
    }

    // These pointers refer to metadata owned by the map index and descriptor.
    const MapType* map_type = &map_it->second;
    const FieldDescriptorProto* value_field = map_type->value_field;
    auto value_type = value_field->type;

    // TODO: Support message map values, including qualified nested message names.
    if (value_type == FieldDescriptorProto::TYPE_MESSAGE ||
        value_type == FieldDescriptorProto::TYPE_GROUP)
    {
        throw std::runtime_error(
            myformat("Unsupported map value type '{0}' for field {1}{2}",
                     pbtype_name(*value_field),
                     msgtype_name_prefix,
                     field.name));
    }

    return map_type;
}


// Generate C++ code for the entire .pbs file
void generator(const FileDescriptorSet& proto)
{
    auto file = proto.file[0];
    package_name_prefix =
        file.package > ""
            ? PB_TYPE_DELIMITER + std::string(file.package) + PB_TYPE_DELIMITER
            : PB_TYPE_DELIMITER;

    for (const auto& message_type: file.message_type)
    {
        std::string field_defs, has_field_defs, encoder, decoder, check_required_fields;
        msgtype_name_prefix = std::string(message_type.name) + PB_TYPE_DELIMITER;

        auto map_types = collect_map_types(message_type);

        for (const auto& field: message_type.field)
        {
            auto map_type = find_map_type(field, map_types);

            // Generate message structure
            auto cpptype_str = cpp_type_as_str(field, map_type);  // C++ type for the field (e.g. "std::vector<int32_t>")
            field_defs += myformat("    {} {}{};\n", cpptype_str, field.name, default_value_str(field));

            if (hasfield_enabled(field)) {
                has_field_defs += myformat("    bool has_{} = false;\n", field.name);
            }

            // Generate message encoding function
            encoder += generate_field_encoder(field, map_type);

            // Generate message decoding function
            decoder += generate_field_decoder(field, map_type);

            if ((field.label == FieldDescriptorProto::LABEL_REQUIRED)  &&  ! option.no_required) {
                check_required_fields += myformat(CHECK_REQUIRED_FIELD_TEMPLATE, message_type.name, field.name);
            }
        }

        if (! option.no_class) {
            std::cout << myformat(CLASS_TEMPLATE, message_type.name, field_defs, has_field_defs);
        }
        if (! option.no_encoder) {
            std::cout << myformat(ENCODER_TEMPLATE, message_type.name, encoder);
        }
        if (! option.no_decoder) {
            std::cout << myformat(DECODER_TEMPLATE, message_type.name, decoder, check_required_fields);
        }
    }
}
